default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['NEU_API_DATABASE_POOL'] || 5 %>

development:
  <<: *default
  database: hometime_development

test:
  <<: *default
  database: hometime_test

production:
  <<: *default
  database: hometime_production
